{% set version = "0.3.4.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppeigen
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppEigen_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppEigen/RcppEigen_{{ version }}.tar.gz
  sha256: 28d4a02011129f9b7a2a2bbe69ec4cca7676b072d5aca9dc1cefa8f96af45136

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.0
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.0

test:
  commands:
    - $R -e "library('RcppEigen')"           # [not win]
    - "\"%R%\" -e \"library('RcppEigen')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/rcpp.eigen.html
  license: GPL-2.0-or-later
  summary: "R and 'Eigen' integration using 'Rcpp'. 'Eigen' is a C++ template library for linear algebra: matrices, vectors, numerical solvers and related algorithms.  It supports dense and sparse matrices on integer, floating point and complex numbers, decompositions of such matrices, and solutions of linear systems. Its
    performance on many algorithms is comparable with some of the best implementations based on 'Lapack' and level-3 'BLAS'. The 'RcppEigen' package includes the header files from the 'Eigen' C++ template library (currently version 3.3.4). Thus users do not need to install 'Eigen' itself in order to use 'RcppEigen'. Since
    version 3.1.1, 'Eigen' is licensed under the Mozilla Public License (version 2); earlier version were licensed under the GNU LGPL version 3 or later. 'RcppEigen' (the 'Rcpp' bindings/bridge to 'Eigen') is licensed under the GNU GPL version 2 or later, as is the rest of 'Rcpp'."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - colinbrislawn
    - conda-forge/r

# Package: RcppEigen
# Type: Package
# Title: 'Rcpp' Integration for the 'Eigen' Templated Linear Algebra Library
# Version: 0.3.3.7.0
# Date: 2019-11-16
# Author: Douglas Bates, Dirk Eddelbuettel, Romain Francois, and Yixuan Qiu; the authors of Eigen for the included version of Eigen
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Copyright: See the file COPYRIGHTS for various Eigen copyright details
# Description: R and 'Eigen' integration using 'Rcpp'. 'Eigen' is a C++ template library for linear algebra: matrices, vectors, numerical solvers and related algorithms.  It supports dense and sparse matrices on integer, floating point and complex numbers, decompositions of such matrices, and solutions of linear systems. Its performance on many algorithms is comparable with some of the best implementations based on 'Lapack' and level-3 'BLAS'. The 'RcppEigen' package includes the header files from the 'Eigen' C++ template library (currently version 3.3.4). Thus users do not need to install 'Eigen' itself in order to use 'RcppEigen'. Since version 3.1.1, 'Eigen' is licensed under the Mozilla Public License (version 2); earlier version were licensed under the GNU LGPL version 3 or later. 'RcppEigen' (the 'Rcpp' bindings/bridge to 'Eigen') is licensed under the GNU GPL version 2 or later, as is the rest of 'Rcpp'.
# License: GPL (>= 2) | file LICENSE
# Depends: R (>= 2.15.1)
# LazyLoad: yes
# LinkingTo: Rcpp
# Imports: Matrix (>= 1.1-0), Rcpp (>= 0.11.0), stats, utils
# Suggests: inline, tinytest, pkgKitten, microbenchmark
# URL: http://dirk.eddelbuettel.com/code/rcpp.eigen.html
# BugReports: https://github.com/RcppCore/RcppEigen/issues
# NeedsCompilation: yes
# Packaged: 2019-11-16 13:45:23.985006 UTC; edd
# Repository: CRAN
# Date/Publication: 2019-11-16 15:40:02 UTC
